### PR TITLE
Added DevOps roadmap to resources

### PR DESCRIPTION
**Pull request by chriscarnold**

### CODE REVIEW

**Comment by vishnus17** [comment]
Hi @chriscarnold . 
Looks like you just took the resource from the PR I made and pushed a new PR.

**Comment by chriscarnold** [comment]
Hi @vishnus17, thank you for reaching out. Wow, that's really unfortunate...It was an honest mistake, I didn't check the PR's and should have noticed that you have already added the exact same resource 30 minutes before me, I mean what are the odds right? The last time I checked was yesterday and noticed that the roadmap would be a cool resource to add as I am still learning how to use git & GitHub (at the time the roadmap wasn't on there). Hope that makes sense and wish you a good weekend. Please let me know if there is anything else that I need to do

**Comment by vishnus17** [comment]
Hey @chriscarnold . All good!

**Comment by chriscarnold** [comment]
Love your github page @vishnus17 !

**Comment by vishnus17** [comment]
Thanks @chriscarnold

**Pull request closed without merging**
