### PR TITLE
adding one of the best resource out there

### PR DESCRIPTION
**Pull request by Chinmay-03**
**the main purpose is that i think  people should get to know about this and they can get help to learn core CS principle's from here** 
Devops is also covered
@rohitg00 
the following text is added 

The OSSU curriculum is a complete education in computer science using online materials.The courses themselves are among the very best in the world, often coming from Harvard, Princeton, MIT, etc.,  high quality in teaching materials and pedagogical principles purpose of including this here is to just make you aware that everything can be learnt online  you just need the patience and will to learn

### CODE REVIEW

**Comment by Chinmay-03** [comment]
if you have any suggestions I'm open to collaborating..

**Comment by rohitg00** [comment]
How this is beneficial in DevOps, Can you please explain more?

**Comment by Chinmay-03** [comment]
> How this is beneficial in DevOps, Can you please explain more?

just to make people aware about it as devops also require some core CS principles 😊

**Comment by rohitg00** [comment]
PLEASE RESOLVE CONFLICTS WITH UPDATED VERSION OF README.

**Comment by Chinmay-03** [comment]
> PLEASE RESOLVE CONFLICTS WITH UPDATED VERSION OF README.

i have resolved feel free to point out if you find any issues

**Pull request closed without merging**
